### ISSUE TITLE
[Feature Request] 인증 관련 페이지

### ISSUE THREAD

**Issue by sangrimlee** [TRIPONG-2022/frontend#9]
# Feature Request

인증 과정에서 필요한 페이지 구현

## Description

인증 과정에서 필요한 페이지를 기본적으로 구현

## ToDo

- [x] 이메일 인증
- [x] 아이디 찾기
- [x] 비밀번호 찾기

**Comment by alicesykim95** [comment]
아이디 찾기/비밀번호 찾기에 대해 질문이 있습니다!

1. 아이디와 비밀번호 찾기에서 이메일 인증이 반드시 필요할까요? 단순히 회원가입시 입력했던 정보 입력으로 검증을 하고 아이디와 비밀번호를 찾을 수 있는 플로우도 괜찮지 않을까해서요!

2. 아이디와 비밀번호 찾기 폼은 이름,  생년원일, 이메일로 동일할까요? 

3. 아이디와 비밀번호 찾기 플로우를 구체적으로 정하지 않은 것 같은데, 프론트쪽에서 가지고 있는 의견 있을까요? 제가 생각하고 있는 플로우는 아래와 같은데 프론트쪽에서 의견이 다르다면 말씀해주세요! 

- 아이디 찾기: 회원가입시 입력했던 정보 입력으로 DB에서 유저 정보 확인 → 확인 후 정보 일치할 시 아이디 화면에 띄우기 

- 비밀번호 찾기: 회원가입시 입력했던 정보 입력으로 DB에서 유저 정보 확인 → 난수를 대체 비밀번호로 보내주고 비밀번호 재설정하도록 함 → 비밀번호 재설정

**Comment by sangrimlee** [comment]
수연님(@alicesykim95) 저도 고민하던 부분인데 질문 주셔서 감사합니다😄 


1. 아이디 찾기와 같은 경우에는 말씀해주신 것처럼 사용자 정보 입력으로 찾는 것도 괜찮을 것 같아요. 하지만, 비밀번호 찾기와 같은 경우는 이메일로 비밀번호 재설정 링크 또는 인증번호와 같은 인증과정이 필요하다고 생각이 드네요.

2. 현재는 이메일만 입력하는 구조로 생각하고 구현하고 있어요. 왜냐하면, 추가 정보를 입력하는 것이 Optional하게 변경되면서, 이름, 생년월일을 이 부분에서 사용할 수 없을 것 같아서 이메일만 사용하는 것을 생각했어요!

3. 제가 생각한 방향은 다음과 같은데, 아이디 찾기는 수연님이 주신 의견으로 해도 좋을 것 같습니다. 하지만, 비밀번호 찾기는 임시 비밀번호보다는 재설정 링크 같은 방식이 더 좋을 것 같아요. 우선, 저희는 아래과 같은 플로우로 생각했습니다.

- 아이디 찾기: 이메일 입력 -> 가입한 이메일이 있다면 해당 이메일로 아이디를 전송 (일부분을 *로 가리거나 전체) 

- 비밀번호 찾기: 이메일 입력 -> 비밀번호 재설정 링크가 있는 이메일 전송 -> 해당 링크로 사용자의 비밀번호 재설정

---

제가 생각하는 비밀번호 찾기와 관련된 참조할만한 사이트 남겨드립니다.

- [Reset Password UI Design Flow](https://www.checklist.design/flows/password)

- [Reset Password Flow Image](https://melodiessim.netlify.app/static/08ab575d080700b793030bacacf71190/511f0/JWTDevPOV.png)

- 위 포스트에서는 JWT랑 현재 사용자 비밀번호로 Hash하는 방식으로 처리하였는데, 내부적인 로직은 뭐가 좋을지는 잘 모르겠네요

**Comment by alicesykim95** [comment]
상림님(@sangrimlee) 자세한 답변 정말 감사합니다! 😄 

생각해보니 말씀하신 것처럼 추가 정보 입력이 Optional하다면, 이메일만 입력 받아 아이디와 비밀번호 찾기를 진행하는 것이 좋겠네요! 

그리고 비밀번호 찾기는 상림님께서 제안해주신 의견에 크게 이견이 없기 때문에 그대로 진행하겠습니다! 반면 아이디 찾기는 
제 의견도 괜찮다고 하셔서 화면에 바로 아이디를 띄우는 방법으로 진행하겠습니다! 이메일로 아이디를 전송해도 전혀 상관없지만 단순히 비밀번호 찾기와 차별을 조금 두고 싶어서요! 

그럼 최종적으로 아래와 같은 플로우로 진행하도록 할게요!

- 아이디 찾기: 이메일 입력 → 아이디 화면에 띄우기 (일부분을 *로 가리거나 전체)

- 비밀번호 찾기: 이메일 입력 → 비밀번호 재설정 링크가 있는 이메일 전송 → 해당 링크로 사용자의 비밀번호 재설정

feat) 앗 깜빡할뻔했는데 공유해주신 참고 사이트 큰 도움되었습니다! 감사합니다!

**Comment by alicesykim95** [comment]
안녕하세요 상림님(@sangrimlee ) 금일 회의 내용을 바탕으로 최종 점검 및 URL 공유건으로 코멘트 남깁니다.

#### [ 이메일 인증 ]

- 플로우: 이메일 입력 → 토큰 생성(백엔드) → 이메일 전송(백엔드) → 유저 링크 접속 → 토큰 유효 확인 요청(프론트) → 토큰 유효 확인 및 권한 부여(백엔드) → 결과와 함께 프론트로 리다이렉트 

#### [ 비밀번호 찾기 ]

- 플로우: 이메일 입력 → 토큰 생성(백엔드) → 이메일 전송(백엔드) → 유저 링크 접속 동시에 토큰 유효 확인 요청(프론트) → 토큰 유효 확인 → 토큰 유효 확인시 새로운 비밀번호 작성 및 재설정 요청(프론트) → 비밀번호 재설정(백엔드) → 결과와 함께 프론트로 리다이렉트

#### [ 프론트에서 구현해주실 내용 ]

- 비밀번호 + 비밀번호 확인 값 일치 
- 비밀번호 찾기에서 재설정 요청시 URL에서 토큰 값과 비밀번호 함께 전송 
- 찾은 아이디 화면에 띄울때 3~5번째 글자 * 처리 

제가 이해한바로는 위와 같아요! 혹시 제가 잘못 이해한 부분 있다면 알려주시고, 링크 공유해주신다고 하셨는데 여기에 남겨주시면 좋을 것 같아요!

**Comment by sangrimlee** [comment]
> 안녕하세요 상림님(@sangrimlee ) 금일 회의 내용을 바탕으로 최종 점검 및 URL 공유건으로 코멘트 남깁니다.
> 
> #### [ 이메일 인증 ]
> * 플로우: 이메일 입력 → 토큰 생성(백엔드) → 이메일 전송(백엔드) → 유저 링크 접속 → 토큰 유효 확인 요청(프론트) → 토큰 유효 확인 및 권한 부여(백엔드) → 결과와 함께 프론트로 리다이렉트
> 
> #### [ 비밀번호 찾기 ]
> * 플로우: 이메일 입력 → 토큰 생성(백엔드) → 이메일 전송(백엔드) → 유저 링크 접속 동시에 토큰 유효 확인 요청(프론트) → 토큰 유효 확인 → 토큰 유효 확인시 새로운 비밀번호 작성 및 재설정 요청(프론트) → 비밀번호 재설정(백엔드) → 결과와 함께 프론트로 리다이렉트
> 
> #### [ 프론트에서 구현해주실 내용 ]
> * 비밀번호 + 비밀번호 확인 값 일치
> * 비밀번호 찾기에서 재설정 요청시 URL에서 토큰 값과 비밀번호 함께 전송
> * 찾은 아이디 화면에 띄울때 3~5번째 글자 * 처리
> 
> 제가 이해한바로는 위와 같아요! 혹시 제가 잘못 이해한 부분 있다면 알려주시고, 링크 공유해주신다고 하셨는데 여기에 남겨주시면 좋을 것 같아요!

안녕하세요 수연님(@alicesykim95)

말씀해주신 플로우대로 진행해주시면 될 것 같아요😃 

이메일 인증이랑 비밀번호 재설정을 위한 URL은 우선적으로 남겨두겠습니다.

- BASE_URL: https://tripong-development.herokuapp.com
- 이메일 인증: /auth/verify-request
- 비밀번호 재설정: /auth/reset-password

나중에 배포할 때는, BASE_URL이 변경될 예정이라서, 환경변수로 저희 URL 설정해주시면 될 것 같아요.

**Comment by alicesykim95** [comment]
알겠습니다! 이대로 진행할게요! 감사합니다 상림님!(@sangrimlee) 😃
